// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvoilgockbqhzgqrejlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2b2lsZ29ja2JxaHpncXJlamxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTc0MjgsImV4cCI6MjA2MDIzMzQyOH0.GE_ZIAkizUOzfnHWsj7ndvNb-g53Br-Z3GuVfJYlf7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);